<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <AssemblyName>IceHaloStack.WinUI.Client</AssemblyName>
    <RootNamespace>IceHaloStack.WinUI.Client</RootNamespace>
  </PropertyGroup>
</Project>
